version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      FLASK_ENV: development
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: toor
      MYSQL_DB: flask_db
    volumes:
      - .:/app

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: flask_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
