version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on: #mysql이 완전히 실행된 후에 실행
      - mysql
    restart: always
    environment: #각 값은 .env파일에서 불러옴
      FLASK_ENV: ${FLASK_ENV}
      FLASK_DEBUG: ${FLASK_DEBUG}
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - .:/app

  mysql:
    image: mysql:8.0
    restart: always
    env_file: # 환경변수 파일 지정
      - .env
    ports:
      - "3307:3306" # 포트 바인딩 오류 제거
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:  # mysql이 실행될 때까지 기다리도록 설정
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s

volumes:
  mysql_data:
